name: flutter_test_beginner
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  pedantic_mono: ^1.21.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
